Repository milvus-io/milvus.io, pull requests merged in 2021-12, with the labels that each got.

#772 add links in demo page
  src/components/demoComponents/floatBord/index.jsx
  src/pages/milvus-demos/index.jsx
  src/pages/milvus-demos/index.module.less
Labels: size/S

#777 Optimize repetitive animation broadcast
  src/components/swiper/index.jsx
  src/components/swiper/index.module.less
Labels: size/L

#781 Update subscribe resource
  src/pages/milvus-demos/index.jsx
Labels: size/XS

#780 remove users page
  src/pages/users.js
Labels: size/L

#779 Fix table font
  src/css/variables/docsStyle.less
Labels: size/XS

#782 Preview
  src/css/variables/docsStyle.less
  src/pages/milvus-demos/index.jsx
  src/pages/users.js
Labels: size/L

#783 Update features
  gatsbyUtils/createPages.js
  src/i18n/layout/en.json
  src/pages/milvus-demos/index.jsx
  src/templates/community.jsx
Labels: size/M

#784 Preview
  gatsbyUtils/createPages.js
  src/i18n/layout/en.json
  src/pages/milvus-demos/index.jsx
  src/templates/community.jsx
Labels: size/M

#785 Fix typo
  src/i18n/layout/cn.json
  src/i18n/layout/en.json
Labels: size/XS

#786 Preview
  src/i18n/layout/cn.json
  src/i18n/layout/en.json
Labels: size/XS

#787 Add word count
  Dockerfile.docs
  gatsby-node.js
  gatsbyUtils/createPages.js
  package.json
  src/templates/docTemplate.less
  yarn.lock
Labels: size/L

#789 Add words count when building app
  Dockerfile.docs
  gatsby-node.js
  gatsbyUtils/createPages.js
  package.json
  src/templates/docTemplate.less
  yarn.lock
Labels: size/L

#791 Hide request url
  .github/workflows/master_aws.yml
  .github/workflows/preview_aws.yml
  gatsbyUtils/createPages.js
Labels: size/M

#792 Preview
  .github/workflows/docker_publish.yml
  .github/workflows/master_aws.yml
  .github/workflows/preview_aws.yml
  gatsbyUtils/createPages.js
Labels: size/L

#793 Hide requerst url
  .env.development
  .env.production
  src/components/demoComponents/infoSubmitter/index.jsx
  src/http/mailchimp.js
Labels: size/S
