Repository milvus-io/milvus.io, pull requests merged in 2021-11, with the labels that each got.

#750 rebuild github button
  package.json
  src/components/button/githubButton/index.jsx
  src/components/button/githubButton/index.module.less
  src/http/http.js
  src/pages/index.jsx
  src/pages/index.less
  yarn.lock
Labels: size/L

#751 modify style of github button
  src/components/button/githubButton/index.module.less
Labels: size/S

#753 Preview
  package.json
  src/components/button/githubButton/index.jsx
  src/components/button/githubButton/index.module.less
  src/http/http.js
  src/pages/index.jsx
  src/pages/index.less
  yarn.lock
Labels: size/L

#755 Preview
  src/pages/milvus-demos/demo.module.less
Labels: size/XS

#758 Modify demo style
  src/components/button/githubButton/index.jsx
  src/components/demoComponents/item/preview.module.less
  src/components/demoComponents/item/previewItem.jsx
Labels: size/S

#760 add swiper to slogan section
  src/components/swiper/index.jsx
  src/components/swiper/index.module.less
  src/pages/index.jsx
Labels: size/L

#761 update theme style
  src/components/blogDetail/blogTag.jsx
  src/components/blogDetail/index.module.less
  src/components/button/index.module.less
  src/components/card/blogCard/v2/index.jsx
  src/components/card/blogCard/v2/index.module.less
  src/components/footer/v2/index.module.less
  src/components/header/v2/constants.jsx
  src/components/header/v2/index.module.less
  src/components/selector/v2/v2.module.less
  src/components/swiper/index.jsx
  src/components/swiper/index.module.less
  src/css/variables/color.less
  src/css/variables/docsStyle.less
  src/images/v2/autoscaling.svg
  src/images/v2/deployment.svg
  src/images/v2/search_icon.svg
  src/images/v2/storage.svg
  src/images/v2/support.svg
  src/pages/index.jsx
  src/pages/index.less
  src/templates/blogTemplate.jsx
  src/templates/blogTemplate.module.less
Labels: size/L

#763 fix en doc blocked by robots.txt issue
  gatsby-config.js
Labels: size/XS

#767 update link color in doc home
  src/components/homeTemplate/homeTemplate.less
  src/pages/tool-sizing.jsx
Labels: size/S

#770 modify font family of doc search modal
  package.json
  src/components/search/algolia.jsx
  src/components/search/index.less
  yarn.lock
Labels: size/S
