Repository milvus-io/milvus.io, pull requests merged in 2022-04, with the labels that each got.

#1022 Preview
  gatsbyUtils/createPages.js
  src/components/seo.js
  src/i18n/en/milvus.json
  src/templates/blogListTemplate.jsx
  src/templates/blogTemplate.jsx
  src/templates/communityTemplate.jsx
  src/templates/docTemplate.js
Labels: size/M

#1040 Update request url of image search demo
  src/http/imageSearch.js
  src/pages/milvus-demos/reverse-image-search.jsx
Labels: size/S

#1042 update demo url
  src/pages/milvus-demos/index.jsx
Labels: size/XS
