Repository milvus-io/milvus.io, pull requests merged in 2022-01, with the labels that each got.

#799 20220107v3fix
  package.json
  src/components/footer/index.jsx
  src/components/footer/index.module.less
  src/components/home/banner.jsx
  src/components/home/banner.less
  src/components/home/code-example.js
  src/components/home/code.jsx
  src/components/home/features.jsx
  src/components/signup/index.module.less
  src/i18n/cn/milvus.json
  src/images/home/cloud.svg
  src/images/home/command.svg
  src/images/home/search.svg
  src/pages/index.jsx
  src/pages/index.less
  src/pages/index.module.less
  src/templates/blogListTemplate.jsx
  src/templates/commonDocTemplate.less
  src/templates/docTemplate.less
  yarn.lock
Labels: size/XXL

#801 Add home translation
  src/components/home/attu.jsx
  src/i18n/cn/milvus.json
  src/i18n/en/milvus.json
  src/pages/index.jsx
Labels: size/M

#802 refine attu
  src/components/home/attu.jsx
  src/images/home/attu_1.jpg
  src/images/home/attu_2.jpg
  src/images/home/attu_3.jpg
  src/pages/index.less
Labels: size/S

#804 20220107v3fix
  src/components/header/index.jsx
  src/components/header/index.module.less
  src/pages/index.jsx
  src/pages/milvus-demos/index.jsx
  src/pages/milvus-demos/reverse-image-search.jsx
  src/templates/blogListTemplate.jsx
  src/templates/blogTemplate.jsx
  src/templates/bootcampTemplate.less
  src/templates/communityTemplate.jsx
Labels: size/M

#807 modify header style
  src/components/githubButton/index.jsx
  src/components/header/index.jsx
  src/components/header/index.module.less
  src/components/home/banner.less
  src/templates/docTemplate.less
Labels: size/M

#809 Refine style
  src/components/home/attu.jsx
  src/pages/index.less
  src/templates/communityTemplate.jsx
  src/templates/docTemplate.less
Labels: size/S

#811 Doc flash issue
  src/http/hooks.js
Labels: size/M

#813 fix mobile header menu click event
  src/components/header/index.jsx
  src/components/header/index.module.less
Labels: size/M

#814 fix header style
  src/components/header/index.module.less
Labels: size/XS

#815 fix build issue
  src/http/hooks.js
Labels: size/S

#821 update docs style
  gatsby-config.js
  src/components/card/HorizontalBlogCard.module.less
  src/css/variables/docsStyle.less
  src/templates/blogTemplate.module.less
  src/templates/docTemplate.less
Labels: size/S

#825 fix menu icon
  src/components/customIconLink/CustomIconLink.module.less
  src/components/customIconLink/index.jsx
  src/css/variables/docsStyle.less
  src/templates/docTemplate.less
Labels: size/S

#826 modify title fonts
  src/pages/common-layout.module.less
Labels: size/XS

#827 Refine homepage style & fix doc flash issue
  src/components/footer/index.module.less
  src/components/githubButton/index.module.less
  src/components/header/index.jsx
  src/components/header/index.module.less
  src/components/home/attu.jsx
  src/components/home/banner.less
  src/components/home/code.jsx
  src/css/variables/color.less
  src/css/variables/main.less
  src/http/hooks.js
  src/images/home/attu_1.jpg
  src/images/home/attu_2.jpg
  src/images/home/attu_3.jpg
  src/images/home/external_link.svg
  src/images/spliter.svg
  src/pages/index.jsx
  src/pages/index.less
  src/pages/index.module.less
  src/templates/communityTemplate.jsx
  src/templates/communityTemplate.less
  src/templates/docTemplate.js
  src/templates/docTemplate.less
Labels: size/L

#828 Change home code section
  src/components/home/code-example.js
  src/components/home/code.jsx
  src/i18n/cn/milvus.json
  src/i18n/en/milvus.json
  src/pages/index.less
Labels: size/L

#830 Update homepage banner
  src/components/home/banner.less
Labels: size/S

#831 Remove warning
  src/components/dialog/FeedbackDialog.jsx
  src/components/footer/index.jsx
  src/components/header/index.jsx
  src/components/home/attu.jsx
  src/components/home/banner.jsx
  src/components/home/code.jsx
  src/components/relatedQuestion/index.jsx
  src/components/tags/index.jsx
  src/http/hooks.js
  src/pages/index.less
  src/pages/tool-sizing.jsx
  src/templates/apiDocTemplate.js
  src/templates/blogListTemplate.jsx
  src/templates/communityTemplate.jsx
Labels: size/L

#832 add milmil bot
  src/components/dialog/FeedbackDialog.jsx
  src/components/header/index.jsx
  src/components/header/index.module.less
  src/components/questionRobot/answerBlock.js
  src/components/questionRobot/index.jsx
  src/components/questionRobot/index.module.less
  src/components/questionRobot/welcomBlock.js
  src/images/icon_bird.svg
  src/images/icon_send.svg
Labels: size/XL

#833 fix tc issues
  src/components/header/index.jsx
  src/components/home/code.jsx
  src/components/leftNavigation/index.jsx
  src/components/leftNavigation/leftNav.less
  src/i18n/cn/milvus.json
  src/i18n/en/milvus.json
  src/utils/index.js
Labels: size/L

#834 Fix mobile community
  src/components/home/banner.jsx
  src/css/variables/docsStyle.less
  src/pages/index.jsx
  src/templates/communityTemplate.less
  src/templates/docTemplate.less
Labels: size/L

#836 fix header display in width-1300
  src/components/header/index.jsx
  src/components/home/banner.less
  src/css/variables/main.less
Labels: size/S

#837 Refine homepage style
  src/components/customIconLink/CustomIconLink.module.less
  src/components/customIconLink/index.jsx
  src/components/home/banner.less
  src/components/home/code.jsx
  src/components/questionRobot/index.jsx
  src/components/relatedQuestion/index.jsx
  src/components/relatedQuestion/relatedQuestion.module.less
  src/components/treeView/ExpansionTreeView.jsx
  src/components/treeView/ExpansionTreeView.less
  src/components/treeView/TocTreeView.jsx
  src/http/hooks.js
  src/pages/index.less
  src/pages/index.module.less
  src/templates/docTemplate.less
Labels: size/L

#838 fix code section
  src/components/home/code.jsx
  src/components/leftNavigation/leftNav.less
  src/pages/index.less
Labels: size/S

#848 Fix issues
  src/components/header/index.module.less
  src/components/home/banner.less
  src/components/home/code.jsx
  src/components/leftNavigation/leftNav.less
  src/components/questionRobot/answerBlock.js
  src/components/questionRobot/index.jsx
  src/components/questionRobot/index.module.less
  src/components/questionRobot/welcomBlock.js
  src/images/milmil_logo.svg
  src/pages/index.module.less
Labels: size/L

#853 Refine doc style
  src/components/card/HorizontalBlogCard.module.less
  src/components/treeView/TocTreeView.jsx
  src/css/variables/docsStyle.less
  src/images/index/bg.svg
  src/templates/docTemplate.less
Labels: size/M

#854 fix style issue under 1440p
  gatsby-node.js
  package.json
  yarn.lock
Labels: size/M

#859 Fix icon link align & revert brands images
  src/components/customIconLink/index.jsx
  src/components/relatedQuestion/relatedQuestion.module.less
  src/components/scoredFeedback/scoredFeedback.module.less
  src/components/treeView/ExpansionTreeView.jsx
  src/components/treeView/ExpansionTreeView.less
  src/images/brands/cmb.png
  src/images/brands/ebay.png
  src/images/brands/ikea.png
  src/images/brands/intuit.png
  src/images/brands/kuaishou.png
  src/images/brands/line.png
  src/images/brands/pingan.png
  src/images/brands/shopee.png
  src/images/brands/smartnews.png
  src/images/brands/vivo.png
  src/images/brands/walmart.png
  src/images/brands/xiaomi.png
Labels: size/M

#866 refine shootingStyle
  src/components/home/banner.less
  src/pages/index.less
Labels: size/M

#871 fix icon and blog style
  src/components/card/BlogCard.module.less
  src/components/customIconLink/index.jsx
  src/components/header/index.jsx
  src/components/header/index.module.less
  src/components/relatedQuestion/index.jsx
  src/components/treeView/ExpansionTreeView.jsx
  src/templates/blogListTemplate.module.less
Labels: size/M

#873 Refine home style
  src/components/footer/index.module.less
  src/components/home/banner.less
  src/components/questionRobot/index.jsx
  src/components/questionRobot/index.less
  src/images/brands/cmb.png
  src/images/brands/ebay.png
  src/images/brands/ikea.png
  src/images/brands/intuit.png
  src/images/brands/kuaishou.png
  src/images/brands/line.png
  src/images/brands/pingan.png
  src/images/brands/shopee.png
  src/images/brands/smartnews.png
  src/images/brands/vivo.png
  src/images/brands/walmart.png
  src/images/brands/xiaomi.png
  src/pages/index.module.less
Labels: size/M

#875 Refine styles
  src/components/footer/index.module.less
  src/components/header/index.module.less
  src/components/home/attu.jsx
  src/components/home/code.jsx
  src/components/questionRobot/index.jsx
  src/css/variables/main.less
  src/pages/index.less
Labels: size/L

#876 Refine attu
  src/components/home/banner.jsx
  src/pages/index.less
  src/templates/communityTemplate.less
Labels: size/S

#883 fix for #881
  src/components/header/index.jsx
  src/components/header/index.module.less
  src/i18n/cn/milvus.json
  src/i18n/en/milvus.json
Labels: size/M

#885 update milmil Icon position
  src/components/questionRobot/index.module.less
Labels: size/S

#886 fix sizing tool
  src/utils/sizingTool.js
Labels: size/XS

#884 fix sizing tool
  src/utils/sizingTool.js
Labels: size/XS

#887 modify subscribe button style
  src/components/signup/index.module.less
Labels: size/XS

#891 fix 2 header issue
  src/components/header/index.jsx
  src/components/header/index.module.less
Labels: size/XL

#892 remove dependence with higlightBlock
  package.json
  src/components/home/code.jsx
  src/pages/index.less
  yarn.lock
Labels: size/M

#894 add recommend blog
  gatsbyUtils/createPages.js
  src/templates/blogListTemplate.jsx
Labels: size/S

#895 add recommend blog
  src/templates/blogListTemplate.jsx
Labels: size/M

#897 fix left nav not located by group topics
  gatsby-node.js
  gatsbyUtils/createPages.js
  src/components/leftNavigation/index.jsx
  src/templates/docTemplate.js
Labels: size/S

#898 add recommend field in frontmatter
  gatsby-node.js
Labels: size/M

#900 fix header style issue
  gatsby-node.js
  src/components/header/index.jsx
  src/components/header/index.module.less
Labels: size/L

#902 adjust header with on doc/community page
  src/components/header/index.jsx
  src/components/header/index.module.less
  src/components/layout/index.jsx
  src/css/variables/docsStyle.less
  src/css/variables/main.less
  src/templates/apiDocTemplate.js
  src/templates/apiDocTemplate.less
  src/templates/communityTemplate.jsx
  src/templates/communityTemplate.less
  src/templates/docTemplate.js
  src/templates/docTemplate.less
Labels: size/M

#899 make tabs scroll instead wrap
  src/css/variables/docsStyle.less
Labels: size/S

#906 add code header
  src/css/variables/docsStyle.less
Labels: size/S

#907 update mservice api
  .env.development
  .env.production
  gatsbyUtils/createPages.js
  src/http/mailchimp.js
Labels: size/S

#908 fix font warning
  gatsby-browser.js
  gatsby-config.js
  package.json
  yarn.lock
Labels: size/M

#903 fix style issue
  src/components/header/index.jsx
  src/components/header/index.module.less
  src/css/variables/main.less
  src/images/spliter.svg
  src/pages/milvus-demos/index.jsx
  src/pages/milvus-demos/index.module.less
  src/templates/blogListTemplate.module.less
  src/templates/bootcamp.jsx
  src/templates/bootcampTemplate.less
Labels: size/M

#909 Add word count
  .env.development
  .env.production
  gatsby-node.js
  gatsbyUtils/createPages.js
  package.json
  src/http/submitEmail.js
  yarn.lock
Labels: size/L

#915 add test info
  gatsbyUtils/createPages.js
Labels: size/XS

#913 add image caption in blog
  src/css/variables/docsStyle.less
  src/templates/blogTemplate.jsx
Labels: size/S

#922 fix header style under 1024px - 1440px
  src/components/header/index.module.less
Labels: size/S

#923 fix blog detail page scrolling issue
  src/templates/blogListTemplate.jsx
Labels: size/M

#914 add throttle to subscribe function
  src/components/signup/index.jsx
  src/components/signup/index.module.less
Labels: size/S

#924 Refine handleJavaFiles to support latest java sdk doc
  gatsbyUtils/sourceNodes.js
  package.json
  yarn.lock
Labels: size/L

#925 update layout of home page
  src/components/home/attu.jsx
  src/i18n/cn/milvus.json
  src/i18n/en/milvus.json
  src/images/brands/baidu.png
  src/images/brands/cmb.png
  src/images/brands/compass.png
  src/images/brands/hunt.png
  src/images/brands/kuaishou.png
  src/images/brands/micro.png
  src/images/brands/mobileye.png
  src/images/brands/moj.png
  src/images/brands/shutterstock.png
  src/images/brands/tencent.png
  src/images/brands/tokopedia.png
  src/pages/index.jsx
  src/pages/index.less
  src/pages/index.module.less
Labels: size/L

#930 update background clolor of start btn
  src/components/header/index.module.less
Labels: size/XS

#936 Adopt changes
  src/components/home/banner.jsx
  src/components/home/banner.less
  src/i18n/en/milvus.json
  src/images/brands/kuaishou.png
  src/pages/index.jsx
Labels: size/M

#940 Fix wraning
  src/components/home/attu.jsx
  src/pages/index.jsx
  src/pages/milvus-demos/index.jsx
  src/templates/docTemplate.less
Labels: size/S

#934 apiDocTemplate add Seo
  src/templates/apiDocTemplate.js
Labels: size/XS

#941 Preview
  src/components/card/BlogCard.module.less
  src/components/home/attu.jsx
  src/components/home/banner.jsx
  src/components/home/banner.less
  src/components/home/code.jsx
  src/i18n/en/milvus.json
  src/images/brands/kuaishou.png
  src/pages/index.jsx
  src/pages/milvus-demos/index.jsx
  src/templates/apiDocTemplate.js
  src/templates/docTemplate.less
Labels: size/L

#943 add max_old_space_size
  .github/workflows/master_aws.yml
  .github/workflows/preview_aws.yml
Labels: size/S
