Repository milvus-io/milvus.io, pull requests merged in 2022-03, with the labels that each got.

#993 Zchart markdown template
  package.json
  src/hooks/doc-dom-operation.jsx
  src/templates/commonDocTemplate.less
  src/templates/docTemplate.js
Labels: size/L

#994 Support benchmark chart
  package.json
  src/components/header/index.jsx
  src/components/home/banner.jsx
  src/hooks/doc-dom-operation.jsx
  src/i18n/cn/milvus.json
  src/i18n/en/milvus.json
  src/templates/commonDocTemplate.less
  src/templates/docTemplate.js
Labels: size/L

#995 [UED-1160] [Add cookie consent dialog for milvus.io]
  package.json
  src/components/header/index.jsx
  src/components/milvusCookieConsent/index.jsx
  src/components/milvusCookieConsent/milvusCookieConsent.module.less
  src/components/questionRobot/index.module.less
  src/i18n/cn/milvus.json
  src/i18n/en/milvus.json
  yarn.lock
Labels: size/XL

#1007 solve issue #988, add reddit and HN share buttons
  src/components/share/hackerNewsShareButton.tsx
  src/components/share/index.jsx
  src/images/blog/hackernews.svg
  src/images/blog/reddit.svg
Labels: size/L

#1014 Preview
  src/components/adjustableMenu/index.jsx
  src/components/adjustableMenu/index.module.less
  src/components/aside/index.jsx
  src/components/header/index.jsx
  src/components/layout/index.jsx
  src/components/leftNavigation/index.jsx
  src/components/leftNavigation/leftNav.module.less
  src/hooks/index.jsx
  src/pages/docsStyle.less
  src/templates/apiDocTemplate.js
  src/templates/communityTemplate.jsx
  src/templates/docTemplate.js
  src/templates/docTemplate.less
  src/templates/parts/DocContent.jsx
Labels: size/XL

#1016 Preview
  src/components/card/DemoCard.module.less
  src/components/header/index.module.less
  src/components/home/code.jsx
  src/components/leftNavigation/leftNav.less
  src/pages/homepage.less
Labels: size/M
