Repository milvus-io/milvus.io, pull requests merged in 2022-02, with the labels that each got.

#954 use self hosted runner on prod build
  .github/workflows/master_aws.yml
Labels: size/XS

#959 Fix doc anchor
  README.md
  src/components/aside/index.jsx
Labels: size/M

#960 imporve header animation,fix logo wall,fix doc home text
  src/components/header/index.jsx
  src/components/header/index.module.less
  src/components/home/attu.jsx
  src/http/submitEmail.js
  src/pages/index.jsx
  src/pages/index.module.less
  src/templates/apiDocTemplate.js
Labels: size/M

#962 Recover sizing tool
  src/components/header/index.jsx
  src/pages/tools/common-layout.module.less
  src/pages/tools/sizing.jsx
Labels: size/S

#964 Chang font of code example
  src/pages/index.less
Labels: size/XS

#967 Modify blog pagetitle
  src/templates/blogListTemplate.jsx
Labels: size/S

#966 social share buttons can go down with scrolling now
  src/templates/blogTemplate.jsx
  src/templates/blogTemplate.module.less
Labels: size/M

#969 Sticky share button: fix the format in CSS
  src/templates/blogTemplate.jsx
  src/templates/blogTemplate.module.less
Labels: size/XS

#973 cache collapse status
  src/components/adjustableMenu/index.jsx
  src/components/adjustableMenu/index.module.less
  src/templates/apiDocTemplate.js
  src/templates/commonDocTemplate.less
  src/templates/communityTemplate.jsx
  src/templates/docTemplate.js
Labels: size/M

#976 add pdf btn
  src/components/aside/index.jsx
  src/i18n/cn/milvus.json
  src/i18n/en/milvus.json
Labels: size/L

#977 add scalable doc content
  src/components/adjustableMenu/index.module.less
  src/templates/apiDocTemplate.js
  src/templates/commonDocTemplate.less
  src/templates/communityTemplate.jsx
  src/templates/communityTemplate.less
  src/templates/docTemplate.js
  src/templates/docTemplate.less
Labels: size/L

#981 add loading to try demo btn
  src/components/card/DemoCard.jsx
  src/components/infoSubmitter/index.jsx
Labels: size/S

#982 Preview
  src/components/card/DemoCard.jsx
  src/components/infoSubmitter/index.jsx
Labels: size/S

#983 make doc content width fixiable
  src/hooks/index.jsx
  src/templates/apiDocTemplate.js
  src/templates/apiDocTemplate.less
  src/templates/commonDocTemplate.less
  src/templates/communityTemplate.jsx
  src/templates/docTemplate.js
  src/templates/docTemplate.less
Labels: size/L
