Repository milvus-io/milvus.io, pull requests merged in 2023-01, with the labels that each got.

#1104 Preview
  .github/workflows/master_aws.yml
  .github/workflows/preview_aws.yml
  gatsby-config.js
  gatsby-node.js
  gatsbyUtils/createPages.js
  gatsbyUtils/docs.js
  gatsbyUtils/utils.js
  gatsbyUtils/version.js
  package.json
  src/components/card/sizingToolCard/index.jsx
  src/components/card/sizingToolCard/index.module.less
  src/components/card/sizingToolCard/sizingConfigCard.jsx
  src/i18n/en/milvus.json
  src/pages/tools/sizing.jsx
  src/pages/tools/sizingTool.module.less
  src/templates/docTemplate.jsx
  src/utils/sizingTool.js
Labels: size/XXL

#1116 add default values to sizing tool
  src/components/card/sizingToolCard/sizingConfigCard.jsx
  src/pages/tools/sizing.jsx
  src/utils/sizingTool.js
Labels: size/L

#1122 Resolve sizingtool warning
  src/pages/tools/sizing.jsx
  src/utils/sizingTool.js
Labels: size/S

#1125 add code copy function
  src/components/card/sizingToolCard/codeBlock.jsx
  src/components/card/sizingToolCard/constants.js
  src/components/card/sizingToolCard/index.module.less
  src/components/code/code.js
  src/pages/tools/sizing.jsx
Labels: size/L

#1127 fix code filter
  src/hooks/doc-dom-operation.jsx
Labels: size/XS
