Repository milvus-io/milvus.io, pull requests merged in 2023-02, with the labels that each got.

#1133 [vdc-1459]adjust style of milvus home page
  src/components/githubButton/index.module.less
  src/components/header/index.module.less
  src/components/home/banner.jsx
  src/components/home/banner.less
Labels: size/L

#1135 hide failed alert of mailchimp
  src/components/signup/index.jsx
Labels: size/XS

#1136 Preview
  src/components/signup/index.jsx
Labels: size/XS

#1137 optimize github button and add slack button in header
  src/components/githubButton/icons.jsx
  src/components/githubButton/index.jsx
  src/components/githubButton/index.module.less
  src/components/header/index.jsx
  src/components/header/index.module.less
Labels: size/L

#1142 Preview
  src/components/githubButton/index.jsx
  src/components/githubButton/index.module.less
  src/components/header/index.jsx
  src/components/header/index.module.less
  src/components/home/banner.jsx
  src/components/home/banner.less
Labels: size/M
