Repository milvus-io/milvus.io, pull requests merged in 2024-05, with the labels that each got.

#1330 Fix broken edit links on Rest API pages
  src/templates/apiDocTemplate.jsx
Labels: size/XS

#1333 Only import inkeep on client
  src/components/inkeepAI/index.jsx
Labels: size/M

#1342 update sizing tool page, convert to ts file
  src/i18n/cn/sizingTool.json
  src/i18n/en/sizingTool.json
  src/i18n/index.ts
  src/pages/tools/sizing.tsx
  src/styles/sizingTool.module.less
  src/utils/sizingTool.ts
Labels: size/XL

#1343 update text on sizing page
  src/i18n/en/sizingTool.json
  src/pages/tools/sizing.tsx
Labels: size/S

#1345 Inkeep tweaks (nextjs version)
  public/inkeep/inkeep-overrides.css
  public/inkeep/milvus-icon-white.png
  public/inkeep/zilliz-grayscale.svg
  src/components/inkeep/InkeepChatButton.tsx
  src/components/layout/docLayout/index.tsx
  src/hooks/use-inkeep-settings.ts
Labels: size/M

#1346 new homepage
  public/images/home/DSPy-logo.png
  public/images/home/any-scale.png
  public/images/home/bhargav.png
  public/images/home/cohere.png
  public/images/home/feature-rich.png
  public/images/home/hay-stack.png
  public/images/home/hugging-face.png
  public/images/home/igor.png
  public/images/home/integrations.png
  public/images/home/lang-chain-logo.png
  public/images/home/lang-chain.png
  public/images/home/llama-index-logo.png
  public/images/home/llama-index.png
  public/images/home/medium.png
  public/images/home/meetup-logo.png
  public/images/home/nandula.png
  public/images/home/open-ai.png
  public/images/home/reusable-code.png
  public/images/home/spark.png
  public/images/home/try-cloud-bg-image.png
  public/images/home/vibrant-community.png
  public/images/home/zilliz-logo.png
  src/components/customLink/index.module.less
  src/components/customLink/index.tsx
  src/components/footer/index.tsx
  src/components/icons/index.tsx
  src/components/socialMedias/index.module.less
  src/components/socialMedias/index.tsx
  src/i18n/en/home.json
  src/pages/backupIndex.js
  src/pages/index.tsx
  src/parts/home/attu/index.jsx
  src/parts/home/banner/index.jsx
  src/parts/home/banner/index.module.less
  src/parts/home/bucket/index.jsx
  src/parts/home/bucket/index.module.less
  src/parts/home/codeExample/code-example.js
  src/parts/home/codeExample/code.jsx
  src/parts/home/codeExample/index.module.less
  src/parts/home/codeExampleSection/index.module.less
  src/parts/home/deploySection/index.module.less
  src/parts/home/deploySection/index.tsx
  src/parts/home/developSection/index.module.less
  src/parts/home/developSection/index.tsx
  src/parts/home/lovedSection/index.module.less
  src/parts/home/lovedSection/index.tsx
  src/parts/home/subscribeSection/index.module.less
  src/parts/home/subscribeSection/index.tsx
  src/parts/home/tryFreeSection/index.module.less
  src/parts/home/tryFreeSection/index.tsx
  src/parts/home/vdbSection/index.module.less
  src/parts/home/vdbSection/index.tsx
  src/styles/mixin.module.less
  src/styles/responsive.module.less
  src/styles/variables.module.less
Labels: size/XXL

#1347 basicly complete new homepage
  src/components/copyCodeButton/index.module.less
  src/components/copyCodeButton/index.tsx
  src/components/customButton/index.module.less
  src/components/customButton/index.tsx
  src/components/customInput/Types.ts
  src/components/customInput/customInput.module.less
  src/components/customInput/customInput.tsx
  src/components/customTabs/index.module.less
  src/components/customTabs/index.tsx
  src/components/header/DescktopHeader.tsx
  src/components/header/index.module.less
  src/components/icons/index.tsx
  src/components/signup/index.jsx
  src/components/signup/index.module.less
  src/components/socialMedias/index.module.less
  src/components/socialMedias/index.tsx
  src/components/subscribe/index.module.less
  src/components/subscribe/index.tsx
  src/consts/externalLinks.ts
  src/consts/links.ts
  src/hooks/index.jsx
  src/http/home.ts
  src/http/submitEmail.js
  src/http/submitEmail.ts
  src/i18n/en/milvus.json
  src/pages/backupIndex.js
  src/pages/index.tsx
  src/pages/milvus-demos/index.jsx
  src/parts/home/deploySection/index.module.less
  src/parts/home/deploySection/index.tsx
  src/parts/home/developSection/index.module.less
  src/parts/home/developSection/index.tsx
  src/parts/home/headerSection/index.module.less
  src/parts/home/headerSection/index.tsx
  src/parts/home/lovedSection/index.tsx
  src/parts/home/subscribeSection/index.module.less
  src/parts/home/subscribeSection/index.tsx
  src/parts/home/tryFreeSection/index.tsx
  src/parts/home/vdbSection/index.module.less
  src/parts/home/vdbSection/index.tsx
  src/styles/mixin.module.less
  src/styles/responsive.module.less
  src/styles/variables.module.less
Labels: size/XXL

#1354 pass git secrets to docker
  .github/workflows/preview_aws.yml
  Preview.Dockerfile
Labels: size/S

#1355 update yml
  .github/workflows/preview_aws.yml
Labels: size/XS

#1362 update env
  src/hooks/use-inkeep-settings.ts
  src/http/home.ts
  src/http/mailchimp.js
  src/http/useCase.ts
Labels: size/M

#1365 Bump inkeep widgets to 0.2.279
  package.json
  pnpm-lock.yaml
Labels: size/S

#1371 add page title
  conf/conf.d/client.conf
  src/pages/docs/[...slug].tsx
  src/pages/docs/[id].tsx
Labels: size/S

#1372 Bump inkeep widgets to version 0.2.280
  package.json
  pnpm-lock.yaml
Labels: size/S

#1376 update production walkflow
  .github/workflows/master_aws.yml
  Builder.Dockerfile
Labels: size/L

#1378 chore: rename production_aws.yml
  .github/workflows/production_aws.yml
Labels: size/XS

#1385 chore: remove gatsby
  package.json
  pnpm-lock.yaml
Labels: size/XXL

#1389 Preview
  next.config.js
  package.json
  public/images/home/integrations.png
  src/parts/home/vdbSection/index.tsx
Labels: size/XS

#1390 style: integrations
  src/parts/home/vdbSection/index.tsx
Labels: size/S

#1392 feat: update links
  conf/conf.d/client.conf
  src/parts/home/lovedSection/index.tsx
Labels: size/S

#1393 fix: typo
  conf/conf.d/client.conf
Labels: size/XS
