Repository milvus-io/milvus.io, pull requests merged in 2024-12, with the labels that each got.

#1709 Preview
  conf/conf.d/client.conf
  src/components/aside/index.module.less
  src/components/aside/index.tsx
  src/styles/docsStyle.less
Labels: size/S

#1711 fix: update blog detail styles
  src/components/card/BlogCard.module.less
  src/pages/blog/[id].jsx
  src/styles/blogDetail.module.less
Labels: size/XS

#1713 fix: update blog keep reading card ui
  src/components/card/BlogCard.module.less
  src/components/card/BlogCard.tsx
  src/pages/blog/[id].jsx
Labels: size/M

#1717 updat esubscribe button
  src/components/card/DemoCard.jsx
  src/components/footer/index.tsx
  src/components/subscribe/index.module.less
  src/components/subscribe/index.tsx
  src/http/submitEmail.ts
  src/pages/blog/index.tsx
  src/pages/index.tsx
  src/pages/milvus-demos/index.jsx
Labels: size/M

#1720 Preview
  src/components/card/DemoCard.jsx
  src/components/footer/index.tsx
  src/components/subscribe/index.module.less
  src/components/subscribe/index.tsx
  src/http/submitEmail.ts
  src/pages/blog/index.tsx
  src/pages/index.tsx
  src/pages/milvus-demos/index.jsx
  src/styles/docsStyle.less
Labels: size/M

#1732 fix: deel img alt
  src/components/language-selector/LanguageSelector.tsx
Labels: size/XS

#1741 fix: fix blog page feedback problems
  src/components/footer/index.tsx
  src/i18n/en/blog.json
  src/pages/blog/index.tsx
  src/styles/blog.module.less
Labels: size/S

#1744 fix: enhance blog list filter performance
  src/pages/blog/index.tsx
Labels: size/M

#1750 [MARK-1686] fix: update blog some ui missing and error
  src/components/card/advCard/index.module.less
  src/components/card/advCard/index.tsx
  src/components/header/DescktopHeader.tsx
  src/pages/blog/[id].jsx
  src/styles/blog.module.less
Labels: size/M

#1751 fix: update blog some ui missing and error
  src/components/card/advCard/index.module.less
  src/components/card/advCard/index.tsx
  src/components/header/DescktopHeader.tsx
  src/pages/blog/[id].jsx
  src/styles/blog.module.less
Labels: size/M
