Repository milvus-io/milvus.io, pull requests merged in 2024-06, with the labels that each got.

#1411 Preview
  src/components/layout/docLayout/index.tsx
  src/pages/api-reference/[language]/[version]/[...slug].tsx
  src/pages/docs/[...slug].tsx
  src/pages/docs/[id].tsx
  src/pages/docs/index.tsx
  src/utils/common.ts
Labels: size/M

#1419 Preview
  src/pages/docs/[id].tsx
  src/parts/docs/docHome/index.tsx
  src/styles/docsStyle.less
  src/utils/blog.utils.ts
Labels: size/S

#1421 Preview
  src/pages/blog/[id].jsx
  src/utils/apiReference.ts
Labels: size/M

#1440 fix doc filter
  src/hooks/doc-dom-operation.jsx
  src/hooks/enhanceCodeBlock.js
  src/styles/docsStyle.less
Labels: size/M

#1439 Preview
  src/components/icons/index.tsx
  src/hooks/doc-dom-operation.jsx
  src/hooks/enhanceCodeBlock.js
  src/pages/_app.tsx
  src/pages/error.tsx
  src/styles/docsStyle.less
  src/styles/error.module.less
Labels: size/L

#1443 switch to gtm container
  src/pages/_app.tsx
Labels: size/S

#1442 feat: remove curly braces
  src/pages/_app.tsx
  src/pages/api-reference/[language]/[version]/[...slug].tsx
Labels: size/S

#1446 feat: import_data redirect to import-data
  conf/conf.d/client.conf
Labels: size/XS

#1449 Preview
  Preview.Dockerfile
  src/components/inkeep/InkeepChatButton.tsx
  src/utils/demo-helper.ts
  src/utils/docs.ts
Labels: size/M

#1453 Preview
  src/consts/externalLinks.ts
  src/pages/api-reference/[language]/[version]/[...slug].tsx
  src/utils/docs.ts
Labels: size/L

#1457 Bump inkeep widgets
  package.json
  pnpm-lock.yaml
Labels: size/L

#1456 Preview
  package.json
  pnpm-lock.yaml
  src/components/treeView/ExpansionTreeView.tsx
  src/utils/apiReference.ts
  src/utils/blog.utils.ts
  src/utils/blogs.ts
  src/utils/docs.ts
  src/utils/index.ts
Labels: size/L

#1462 update style of disable feedback button
  src/components/aside/index.module.less
Labels: size/S

#1465 Preview
  src/components/aside/feedback.tsx
  src/components/aside/index.jsx
  src/components/aside/index.module.less
  src/components/aside/index.tsx
  src/components/dialog/Dialog.jsx
  src/components/icons/index.tsx
  src/i18n/en/docs.json
  src/i18n/index.ts
  src/pages/api-reference/[language]/[version]/[...slug].tsx
  src/pages/docs/[...slug].tsx
  src/pages/docs/[id].tsx
  src/parts/docs/anchorTree/index.jsx
  src/parts/docs/anchorTree/index.module.less
  src/types/docs.ts
  src/utils/common.ts
Labels: size/XL

#1470 Preview
  src/hooks/enhanceCodeBlock.ts
Labels: size/S

#1471 upgrade doc anchors
  src/components/aside/index.module.less
  src/components/aside/index.tsx
  src/hooks/doc-anchor.jsx
  src/hooks/doc-anchor.ts
  src/i18n/en/docs.json
  src/pages/docs/[...slug].tsx
  src/pages/docs/[id].tsx
  src/parts/docs/anchorTree/index.tsx
  src/parts/home/productionSection/ProductionSection.tsx
Labels: size/L

#1472 Preview
  src/components/aside/feedback.tsx
  src/components/aside/index.module.less
  src/components/aside/index.tsx
  src/hooks/doc-anchor.jsx
  src/hooks/doc-anchor.ts
  src/i18n/en/docs.json
  src/pages/docs/[...slug].tsx
  src/pages/docs/[id].tsx
  src/parts/docs/anchorTree/index.tsx
  src/parts/home/productionSection/ProductionSection.tsx
Labels: size/L

#1475 resolve duplicated meta description
  src/components/aside/index.tsx
  src/i18n/en/docs.json
  src/pages/api-reference/[language]/[version]/[...slug].tsx
  src/pages/docs/[...slug].tsx
  src/pages/docs/[id].tsx
  src/pages/docs/index.tsx
Labels: size/M

#1477 Preview
  src/components/aside/index.tsx
  src/i18n/en/docs.json
  src/pages/api-reference/[language]/[version]/[...slug].tsx
  src/pages/docs/[...slug].tsx
  src/pages/docs/[id].tsx
  src/pages/docs/index.tsx
  src/utils/apiReference.ts
Labels: size/L

#1481 update api page title
  src/pages/api-reference/[language]/[version]/[...slug].tsx
Labels: size/XS

#1483 Fix website issues
  conf/conf.d/client.conf
  src/pages/404.tsx
  src/styles/404.module.less
  src/styles/variables.module.less
Labels: size/L

#1486 Preview
  conf/conf.d/client.conf
Labels: size/M

#1488 Preview
  src/components/aside/feedback.tsx
  src/components/aside/index.module.less
  src/i18n/en/docs.json
  src/pages/_document.tsx
  src/pages/api-reference/[language]/[version]/[...slug].tsx
  src/types/docs.ts
Labels: size/M
