Repository milvus-io/milvus.io, pull requests merged in 2024-09, with the labels that each got.

#1587 feat: meta title i18n
  src/components/localization/DocHome.tsx
  src/components/search/agloia.tsx
  src/i18n/cn/docs.json
  src/i18n/de/docs.json
  src/i18n/en/docs.json
  src/i18n/es/docs.json
  src/i18n/fr/docs.json
  src/i18n/it/docs.json
  src/i18n/ja/docs.json
  src/i18n/ko/docs.json
  src/i18n/pt/docs.json
Labels: size/S

#1589 fix: api-reference title
  src/pages/api-reference/[language]/[version]/[...slug].tsx
Labels: size/S

#1590 fix: doc detail headingContent
  src/components/localization/CreateDocDetailProps.ts
  src/components/localization/CreateDocSlugProps.ts
Labels: size/XS

#1601 add pagination to milvus blog
  src/components/card/BlogCard.tsx
  src/components/cookieConsent/index.module.less
  src/components/ui/pagination.tsx
  src/pages/blog/index.jsx
  src/pages/blog/index.tsx
  src/parts/home/lovedSection/index.module.less
  src/styles/blog.module.less
  src/styles/mixin.module.less
  src/utils/blog.utils.ts
Labels: size/XL

#1603 Preview
  src/components/card/BlogCard.module.less
  src/components/card/BlogCard.tsx
  src/components/cookieConsent/index.module.less
  src/components/ui/pagination.tsx
  src/pages/blog/index.jsx
  src/pages/blog/index.tsx
  src/parts/home/lovedSection/index.module.less
  src/styles/blog.module.less
  src/styles/mixin.module.less
  src/utils/blog.utils.ts
Labels: size/XL

#1611 Preview
  public/images/demos/chemical-search.svg
  public/images/demos/chemical-structure-search.png
  public/images/demos/hybrid-search.png
  public/images/demos/image-search.png
  public/images/demos/multimodal-image-search.jpeg
  public/images/demos/multimodal-image-search.png
  public/images/demos/oss-chat.png
  public/images/demos/ossChat.png
  src/components/card/DemoCard.jsx
  src/components/card/DemoCard.module.less
  src/i18n/en/demo.json
  src/pages/milvus-demos/index.jsx
  src/styles/milvusDemos.module.less
Labels: size/L

#1614 restore data node and query node
  src/pages/tools/sizing.tsx
Labels: size/M

#1620 add diskann to sizing tool
  src/components/card/sizingToolCard/constants.js
  src/components/card/sizingToolCard/constants.ts
  src/components/card/sizingToolCard/index.jsx
  src/pages/tools/sizing.tsx
  src/utils/sizingTool.ts
Labels: size/L

#1633 Preview
  src/styles/docsStyle.less
Labels: size/XS

#1635 fix: restful mdx docs
  src/components/mdx/rest-space/BaseURL.tsx
  src/components/mdx/rest-space/RestSpace.module.css
  src/components/mdx/rest-space/RestSpace.tsx
  src/components/mdx/rest-space/utils.ts
  src/utils/apiReference.ts
  src/utils/docs.ts
  src/utils/restful.ts
Labels: size/M

#1637 style: CodeBlock
  src/components/mdx/rest-space/CodeBlock.tsx
Labels: size/XS

#1645 Preview
  src/pages/blog/[id].jsx
  src/styles/blogDetail.module.less
Labels: size/S
