Repository milvus-io/milvus.io, pull requests merged in 2024-08, with the labels that each got.

#1549 Preview
  src/i18n/en/home.json
Labels: size/XS

#1553 update nginx check
  .github/workflows/master_aws.yml
  .github/workflows/preview_aws.yml
  .github/workflows/verify_nginx.yml
  conf/conf.d/client.conf
Labels: size/M

#1557 add homepage brand wall
  public/images/home/brands/at&t.png
  public/images/home/brands/bosch.png
  public/images/home/brands/compass.png
  public/images/home/brands/ebay.png
  public/images/home/brands/ibm.png
  public/images/home/brands/ikea.png
  public/images/home/brands/inflection.png
  public/images/home/brands/intuit.png
  public/images/home/brands/line.png
  public/images/home/brands/moj.png
  public/images/home/brands/new-relic.png
  public/images/home/brands/nvidia.png
  public/images/home/brands/omers.png
  public/images/home/brands/paypal.png
  public/images/home/brands/roblox.png
  public/images/home/brands/sales-force.png
  public/images/home/brands/shopee.png
  public/images/home/brands/shutter-stock.png
  public/images/home/brands/smart-news.png
  public/images/home/brands/tokopedia.png
  public/images/home/brands/trend.png
  public/images/home/brands/users.png
  public/images/home/brands/walmart.png
  public/images/home/brands/zip-recruiter.png
  public/images/home/image-search.png
  public/images/home/multimodal-search.png
  public/images/home/rag.png
  src/components/icons/SocialMedia.tsx
  src/i18n/en/home.json
  src/pages/index.tsx
  src/parts/home/developSection/index.tsx
  src/parts/home/productionSection/ProductionSection.tsx
  src/parts/home/productionSection/index.module.less
  src/styles/home.module.less
  src/styles/variables.module.less
Labels: size/L

#1559 update homepage, update code block
  public/images/home/DSPy-logo.png
  public/images/home/lang-chain-logo.png
  public/images/home/llama-index-logo.png
  src/i18n/en/home.json
  src/parts/home/developSection/index.module.less
  src/parts/home/developSection/index.tsx
  src/styles/docsStyle.less
Labels: size/M

#1563 Preview
  src/components/customButton/index.module.less
  src/components/customButton/index.tsx
  src/components/footer/index.tsx
  src/components/header/DescktopHeader.tsx
  src/components/header/Logos.jsx
  src/components/icons/SocialMedia.tsx
  src/components/subscribe/index.module.less
  src/components/subscribe/index.tsx
  src/pages/milvus-demos/index.jsx
  src/parts/home/codeExampleSection/index.module.less
  src/parts/home/deploySection/index.module.less
  src/parts/home/developSection/index.module.less
  src/parts/home/developSection/index.tsx
  src/parts/home/headerSection/index.tsx
  src/parts/home/lovedSection/index.module.less
  src/parts/home/subscribeSection/index.module.less
  src/parts/home/vdbSection/index.module.less
  src/styles/milvusDemos.module.less
  src/styles/variables.module.less
  tailwind.config.js
Labels: size/L

#1576 add multimodal image search entrance
  public/images/demos/multimodal-image-search.jpeg
  src/components/card/DemoCard.jsx
  src/consts/externalLinks.ts
  src/i18n/en/demo.json
  src/i18n/index.ts
  src/pages/milvus-demos/index.jsx
  src/parts/home/developSection/index.tsx
Labels: size/L

#1577 Preview
  public/images/demos/multimodal-image-search.jpeg
  src/components/card/DemoCard.jsx
  src/consts/externalLinks.ts
  src/i18n/en/demo.json
  src/i18n/index.ts
  src/pages/milvus-demos/index.jsx
  src/parts/home/developSection/index.tsx
Labels: size/L

#1580 fix: docs
  src/components/language-selector/LanguageSelector.tsx
  src/pages/_document.tsx
Labels: size/M
