Repository milvus-io/milvus.io, pull requests merged in 2024-11, with the labels that each got.

#1682 disable / for algolia
  src/components/search/agloia.tsx
Labels: size/S

#1696 feat: new design for blog page
  src/components/card/BlogCard.module.less
  src/components/card/BlogCard.tsx
  src/components/card/advCard/index.module.less
  src/components/icons/index.tsx
  src/components/share/index.module.less
  src/pages/blog/[id].jsx
  src/parts/blogs/blogAnchors/index.jsx
  src/parts/blogs/blogAnchors/index.module.less
  src/styles/blogDetail.module.less
  src/styles/docsStyle.less
  src/styles/variables.module.less
Labels: size/L

#1697 fix: add shadow to cookie consent
  src/components/cookieConsent/index.module.less
Labels: size/XS

#1703 fix: update blog docs styles
  src/components/layout/docLayout/index.tsx
  src/components/share/index.module.less
  src/pages/blog/[id].jsx
  src/styles/blogDetail.module.less
  src/styles/docsStyle.less
  src/styles/variables.module.less
Labels: size/M

#1707 Preview
  Nginx.Dockerfile
  conf/conf.d/client.conf
  scripts/pre-commit.js
Labels: size/M
