Repository milvus-io/milvus.io, pull requests merged in 2025-05, with the labels that each got.

#1979 Upgrade dependency
  package.json
  pnpm-lock.yaml
Labels: size/M

#1980 Preview
  package.json
  pnpm-lock.yaml
Labels: size/M

#1991 add llmx.text to root dirctory
  Builder.Dockerfile
  llms.txt
Labels: size/L

#1995 Preview
  src/parts/sizing/resultSection.tsx
  src/utils/sizingTool.ts
Labels: size/M

#1996 chore: update nginx rewrite rules
  conf/conf.d/client.conf
Labels: size/XS
