Repository milvus-io/milvus.io, pull requests merged in 2025-03, with the labels that each got.

#1895 update community link
  src/components/header/DescktopHeader.tsx
  src/components/header/mobileHeader.tsx
  src/consts/links.ts
Labels: size/XS

#1901 fix use case page
  src/parts/intro/UseCase.tsx
  src/styles/reset.css
Labels: size/S

#1902 Preview
  conf/conf.d/client.conf
  src/components/header/DescktopHeader.tsx
  src/components/header/index.tsx
  src/components/header/mobileHeader.tsx
  src/components/layout/commonLayout/index.tsx
  src/pages/milvus-demos/reverse-image-search.jsx
  src/parts/intro/UseCase.tsx
  src/styles/reset.css
Labels: size/M

#1906 Preview
  src/parts/sizing/formSection.tsx
  src/utils/sizingTool.ts
Labels: size/M

#1908 Preview
  conf/conf.d/client.conf
Labels: size/XS

#1912 fix: nginx lang redirect
  conf/conf.d/client.conf
Labels: size/S

#1911 feat: api reference anchor
  src/components/localization/DocDetail.tsx
  src/hooks/use-anchor-event-listener.tsx
  src/pages/api-reference/[language]/[version]/[...slug].tsx
Labels: size/L

#1917 fix: dependency
  Builder.Dockerfile
  Preview.Dockerfile
Labels: size/S

#1919 Preview
  conf/conf.d/client.conf
  public/favicon.ico
  src/pages/_app.tsx
Labels: size/S

#1927 update style of blog card
  src/components/localization/BlogHome.tsx
  src/styles/blog.module.less
Labels: size/S

#1931 update utm tracking params
  src/components/banner/index.tsx
  src/components/card/advCard/index.tsx
  src/components/footer/index.tsx
  src/components/header/DescktopHeader.tsx
  src/components/header/mobileHeader.tsx
  src/consts/links.ts
  src/hooks/use-utm-track-path.tsx
  src/pages/ai-quick-reference/[id].tsx
  src/pages/tools/sizing.tsx
  src/parts/blogs/zillizAdv/index.tsx
  src/parts/contact/Contact.tsx
  src/parts/home/deploySection/index.tsx
  src/parts/home/headerSection/index.tsx
Labels: size/M
