Repository milvus-io/milvus.io, pull requests merged in 2025-04, with the labels that each got.

#1942 feat: docs title tag
  package.json
  pnpm-lock.yaml
  src/pages/api-reference/[language]/[version]/[...slug].tsx
  src/pages/api-reference/restful/[version]/[...slug].tsx
  src/styles/docsStyle.less
  src/types/docs.ts
  src/utils/apiReference.ts
  src/utils/mdx.ts
  src/utils/restful.ts
Labels: size/M

#1943 pref: verify nginx
  .github/workflows/verify_nginx.yml
Labels: size/XS

#1945 Preview
  .github/workflows/verify_nginx.yml
  package.json
  pnpm-lock.yaml
  src/components/aside/index.tsx
  src/pages/api-reference/[language]/[version]/[...slug].tsx
  src/pages/api-reference/restful/[version]/[...slug].tsx
  src/styles/docsStyle.less
  src/types/docs.ts
  src/utils/apiReference.ts
  src/utils/mdx.ts
  src/utils/restful.ts
Labels: size/L

#1952 Preview
  i18n-watcher/cache/faq.json
  src/components/customButton/index.tsx
  src/http/faq.ts
  src/i18n/ar/faq.json
  src/i18n/cn/faq.json
  src/i18n/de/faq.json
  src/i18n/en/faq.json
  src/i18n/es/faq.json
  src/i18n/fr/faq.json
  src/i18n/id/faq.json
  src/i18n/it/faq.json
  src/i18n/ja/faq.json
  src/i18n/ko/faq.json
  src/i18n/pt/faq.json
  src/i18n/ru/faq.json
  src/i18n/zh-hant/faq.json
  src/pages/ai-quick-reference/[id].tsx
  src/pages/ai-quick-reference/index.tsx
  src/styles/faq.module.less
Labels: size/L

#1958 update dependencies
  package.json
  pnpm-lock.yaml
Labels: size/XXL

#1962 update sizingtool calculator
  i18n-watcher/changes/sizingTool.json
  src/i18n/en/sizingTool.json
  src/pages/tools/sizing.tsx
  src/parts/sizing/dependencyComponent.tsx
  src/parts/sizing/formSection.tsx
  src/styles/sizingTool.module.less
  src/utils/sizingTool.ts
Labels: size/M

#1972 update blog meta info, upgrade blog search function
  src/components/localization/BlogDetail.tsx
  src/components/localization/BlogHome.tsx
Labels: size/S

#1976 feat: code block support diff lang
  package.json
  pnpm-lock.yaml
Labels: size/S

#1977 feat: preview_aws.yml use web-content preview branch
  .github/workflows/preview_aws.yml
Labels: size/XS
