Repository milvus-io/milvus.io, pull requests merged in 2025-01, with the labels that each got.

#1754 restore zilliz cloud advertisement
  src/components/header/index.tsx
  src/styles/blogDetail.module.less
  src/styles/variables.module.less
Labels: size/S

#1759 update milvus demo page
  public/images/demos/ask-ai.png
  src/components/card/DemoCard.tsx
  src/i18n/en/demo.json
  src/pages/milvus-demos/index.tsx
Labels: size/L

#1760 [MARK-1687] fix: homepage font refinement
  src/components/customTabs/index.tsx
  src/components/footer/index.tsx
  src/i18n/en/home.json
  src/pages/index.tsx
  src/parts/home/codeExampleSection/index.module.less
  src/parts/home/deploySection/index.module.less
  src/parts/home/developSection/index.module.less
  src/parts/home/developSection/index.tsx
  src/parts/home/headerSection/index.tsx
  src/parts/home/lovedSection/index.module.less
  src/parts/home/subscribeSection/index.module.less
  src/parts/home/subscribeSection/index.tsx
  src/parts/home/tryFreeSection/index.module.less
  src/parts/home/tryFreeSection/index.tsx
  src/parts/home/vdbSection/index.module.less
Labels: size/L

#1765 fix: update homepage some ui details
  src/components/header/DescktopHeader.tsx
  src/pages/index.tsx
  src/parts/home/deploySection/index.module.less
  src/parts/home/vdbSection/index.module.less
Labels: size/S

#1769 fix: update ai dev tools btn hover style
  src/parts/home/tryFreeSection/index.module.less
  src/parts/home/tryFreeSection/index.tsx
Labels: size/S

#1770 fix: fix ai tool btn hover style
  src/parts/home/tryFreeSection/index.module.less
  src/parts/home/tryFreeSection/index.tsx
Labels: size/XS

#1772 update copy on demo page
  src/i18n/en/demo.json
Labels: size/XS

#1773 fix: nav link menu hover error
  src/components/header/DescktopHeader.tsx
Labels: size/M

#1774 update copy of sizingtool, fix calculate lgic
  src/components/sizing/sizingRange/index.tsx
  src/i18n/en/blog.json
  src/i18n/en/sizingTool.json
  src/pages/tools/sizing.tsx
  src/parts/blogs/zillizAdv/index.tsx
  src/parts/sizing/dependencyComponent.tsx
  src/parts/sizing/formSection.tsx
  src/parts/sizing/index.module.less
  src/parts/sizing/milvusComponent.tsx
  src/parts/sizing/resultSection.tsx
  src/types/sizing.ts
  src/utils/sizingTool.ts
Labels: size/L

#1776 adjust order of demos
  src/pages/milvus-demos/index.tsx
Labels: size/M

#1781 fix: update i18n text
  src/i18n/en/blog.json
Labels: size/XS

#1782 fix: update i18n text
  src/i18n/en/blog.json
Labels: size/XS

#1791 adjust style of sizingtool
  src/parts/sizing/resultSection.tsx
  src/styles/sizingTool.module.less
Labels: size/XS

#1801 Preview
  package.json
  pnpm-lock.yaml
  public/images/contact/contact-bg.png
  src/i18n/en/contact.json
  src/i18n/index.ts
  src/pages/_app.tsx
  src/pages/contact.tsx
Labels: size/L

#1803 adjust responsive style of contact entrance
  src/components/header/DescktopHeader.tsx
  src/components/header/mobileHeader.jsx
  src/i18n/en/header.json
Labels: size/S

#1813 fix: remove unused props
  src/components/localization/DocHome.tsx
Labels: size/S

#1814 style: translation ui
  src/components/footer/index.tsx
  src/components/language-selector/LanguageSelector.tsx
  src/i18n/ar/home.json
  src/i18n/cn/home.json
  src/i18n/de/home.json
  src/i18n/en/home.json
  src/i18n/es/home.json
  src/i18n/fr/home.json
  src/i18n/id/home.json
  src/i18n/it/home.json
  src/i18n/ja/home.json
  src/i18n/ko/home.json
  src/i18n/pt/home.json
  src/i18n/ru/home.json
  src/i18n/zh-hant/home.json
  src/pages/[lang]/index.tsx
  src/pages/index.tsx
  src/parts/home/meta/HomeMeta.tsx
Labels: size/L

#1815 update homepage
  src/components/footer/index.tsx
  src/i18n/ar/home.json
  src/i18n/cn/home.json
  src/i18n/de/home.json
  src/i18n/en/home.json
  src/i18n/es/home.json
  src/i18n/fr/home.json
  src/i18n/id/home.json
  src/i18n/it/home.json
  src/i18n/ja/home.json
  src/i18n/ko/home.json
  src/i18n/pt/home.json
  src/i18n/ru/home.json
  src/i18n/zh-hant/home.json
  src/pages/index.tsx
  src/parts/home/developSection/index.module.less
Labels: size/M

#1819 feat: i18n sync translation
  .github/workflows/i18n_translation.yml
  i18n-watcher/cache/404.json
  i18n-watcher/cache/blog.json
  i18n-watcher/cache/community.json
  i18n-watcher/cache/contact.json
  i18n-watcher/cache/demo.json
  i18n-watcher/cache/docs.json
  i18n-watcher/cache/header.json
  i18n-watcher/cache/home.json
  i18n-watcher/cache/intro.json
  i18n-watcher/cache/milvus.json
  i18n-watcher/cache/sizingTool.json
  i18n-watcher/cache/useCase.json
  i18n-watcher/const.js
  i18n-watcher/index.js
  i18n-watcher/scan.js
  i18n-watcher/translate-changes.js
  i18n-watcher/utils.js
  package.json
  pnpm-lock.yaml
Labels: size/XXL
