Repository milvus-io/milvus.io, pull requests merged in 2025-02, with the labels that each got.

#1820 fix: blog lang build
  src/components/localization/CreateBlogDetailProps.ts
Labels: size/XS

#1821 Preview
  .github/workflows/i18n_translation.yml
  i18n-watcher/cache/404.json
  i18n-watcher/cache/blog.json
  i18n-watcher/cache/community.json
  i18n-watcher/cache/contact.json
  i18n-watcher/cache/demo.json
  i18n-watcher/cache/docs.json
  i18n-watcher/cache/header.json
  i18n-watcher/cache/home.json
  i18n-watcher/cache/intro.json
  i18n-watcher/cache/milvus.json
  i18n-watcher/cache/sizingTool.json
  i18n-watcher/cache/useCase.json
  i18n-watcher/const.js
  i18n-watcher/index.js
  i18n-watcher/scan.js
  i18n-watcher/translate-changes.js
  i18n-watcher/utils.js
  package.json
  pnpm-lock.yaml
  src/components/localization/CreateBlogDetailProps.ts
Labels: size/XXL

#1823 Preview
  i18n-watcher/cache/header.json
  i18n-watcher/cache/milvus.json
  src/components/footer/index.tsx
  src/components/language-selector/LanguageSelector.tsx
  src/i18n/ar/header.json
  src/i18n/ar/milvus.json
  src/i18n/cn/header.json
  src/i18n/cn/milvus.json
  src/i18n/de/header.json
  src/i18n/de/milvus.json
  src/i18n/en/header.json
  src/i18n/en/milvus.json
  src/i18n/es/header.json
  src/i18n/es/milvus.json
  src/i18n/fr/header.json
  src/i18n/fr/milvus.json
  src/i18n/id/header.json
  src/i18n/id/milvus.json
  src/i18n/it/header.json
  src/i18n/it/milvus.json
  src/i18n/ja/header.json
  src/i18n/ja/milvus.json
  src/i18n/ko/header.json
  src/i18n/ko/milvus.json
  src/i18n/pt/header.json
  src/i18n/pt/milvus.json
  src/i18n/ru/header.json
  src/i18n/ru/milvus.json
  src/i18n/zh-hant/header.json
  src/i18n/zh-hant/milvus.json
Labels: size/XXL

#1825 revert debug code
  public/sw.js
  src/pages/_app.tsx
  src/parts/tutorials/Demo.tsx
Labels: size/L

#1827 Preview
  public/sw.js
  src/components/footer/index.tsx
  src/components/layout/docLayout/index.module.less
  src/components/layout/docLayout/index.tsx
  src/components/localization/BlogDetail.tsx
  src/parts/tutorials/Demo.tsx
Labels: size/M

#1829 Preview
  i18n-watcher/changes/header.json
  src/i18n/en/header.json
Labels: size/XS

#1831 chore: docs rewrite
  conf/conf.d/client.conf
Labels: size/XS

#1834 fix: translate workflow
  i18n-watcher/translate-changes.js
Labels: size/XS

#1836 Preview
  i18n-watcher/cache/home.json
  i18n-watcher/translate-changes.js
  src/components/breadcrumb/index.module.less
  src/components/breadcrumb/index.tsx
  src/components/icons/index.tsx
  src/components/localization/BlogDetail.tsx
  src/components/localization/DocDetail.tsx
  src/hooks/use-breadcrumb-lables.tsx
  src/i18n/ar/home.json
  src/i18n/cn/home.json
  src/i18n/de/home.json
  src/i18n/en/home.json
  src/i18n/es/home.json
  src/i18n/fr/home.json
  src/i18n/id/home.json
  src/i18n/it/home.json
  src/i18n/ja/home.json
  src/i18n/ko/home.json
  src/i18n/pt/home.json
  src/i18n/ru/home.json
  src/i18n/zh-hant/home.json
  src/pages/api-reference/[language]/[version]/[...slug].tsx
  src/pages/api-reference/restful/[version]/[...slug].tsx
  src/parts/docs/docContent/index.tsx
  src/styles/blogDetail.module.less
  src/styles/restful.module.less
Labels: size/L

#1837 chore: dosc migration rewrite
  conf/conf.d/client.conf
Labels: size/S

#1839 feat: make keep reading never empty
  src/components/localization/CreateBlogDetailProps.ts
Labels: size/S

#1843 update discord link
  src/consts/externalLinks.ts
Labels: size/XS

#1846 Preview
  .vscode/settings.json
  src/components/banner/index.module.less
  src/components/header/mobileHeader.module.less
  src/components/layout/docLayout/index.module.less
  src/parts/docs/docHome/index.module.less
  src/styles/variables.module.less
Labels: size/S

#1850 fix style on mobile
  src/components/banner/index.module.less
  src/components/header/DescktopHeader.tsx
  src/components/header/index.module.less
  src/components/header/mobileHeader.module.less
  src/components/layout/docLayout/index.module.less
  src/styles/blog.module.less
  src/styles/mixin.module.less
  src/styles/variables.module.less
Labels: size/L

#1851 Preview
  i18n-watcher/cache/intro.json
  i18n-watcher/changes/intro.json
  src/components/banner/index.module.less
  src/components/header/DescktopHeader.tsx
  src/components/header/index.module.less
  src/components/header/mobileHeader.module.less
  src/components/layout/docLayout/index.module.less
  src/i18n/ar/intro.json
  src/i18n/cn/intro.json
  src/i18n/de/intro.json
  src/i18n/es/intro.json
  src/i18n/fr/intro.json
  src/i18n/id/intro.json
  src/i18n/it/intro.json
  src/i18n/ja/intro.json
  src/i18n/ko/intro.json
  src/i18n/pt/intro.json
  src/i18n/ru/intro.json
  src/i18n/zh-hant/intro.json
  src/styles/blog.module.less
  src/styles/mixin.module.less
  src/styles/variables.module.less
Labels: size/L

#1853 optimize style of doc home on mobile
  src/components/card/HorizontalBlogCard.module.less
  src/parts/docs/docHome/index.module.less
Labels: size/S

#1864 Preview
  package.json
  pnpm-lock.yaml
  src/components/localization/BlogDetail.tsx
Labels: size/S

#1873 Preview
  package.json
  pnpm-lock.yaml
Labels: size/S

#1866 add zilliz logo to milvus page
  public/images/layout/lf-ai-logo.svg
  public/images/layout/milvus-logo.svg
  public/images/layout/zilliz-logo.svg
  src/components/footer/index.tsx
  src/components/header/DescktopHeader.tsx
  src/components/header/Logos.tsx
  src/components/header/index.module.less
  src/components/header/mobileHeader.module.less
  src/components/header/mobileHeader.tsx
  src/consts/externalLinks.ts
  src/parts/sizing/resultSection.tsx
Labels: size/L

#1876 add community banner to docs toc section
  i18n-watcher/changes/docs.json
  public/images/docs/office-hours.svg
  src/components/aside/index.module.less
  src/components/aside/index.tsx
  src/components/localization/DocDetail.tsx
  src/i18n/en/docs.json
  src/pages/api-reference/[language]/[version]/[...slug].tsx
Labels: size/L
